name: Update README

on:
  schedule:
    - cron: '*/30 * * * *' # Her 30 dakikada bir çalışır
  workflow_dispatch: # Manuel çalıştırmak istersen

jobs:
  update-readme:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    steps:
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "chore: update recent activity"
          MAX_LINES: 1 # Sadece en son commit attığın projeyi görmen için 1 yaptık
